#!groovy

pipeline {
    agent any
stages{
    stage('Build Image') {
	steps {
        /* Let's make sure we have the repository cloned to our workspace */
         sh 'git config user.email "bredemi@yahoo.com"'
	 sh 'git config user.name "emeka"'
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PerBuildTag']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/mekulaventure/Jenkinsdockerproject.git']]])
        sh 'pwd'
	sh 'ls' 
        sh 'cd ~/workspace/MyTest/project'
	sh 'ls project'
        sh 'FROM jenkins/jenkins:lts'
	sh 'USER root'
        sh 'RUN apt-get update'
        sh 'RUN apt-get install -y \'
	sh 'project/mytest.sh'
		    }
	    }
	}
    }

