pipeline {
     agent any
     stages {
          stage('Build Image') {
               steps {
                  app = docker.build("emma1")
               }
          }
          stage('Second Stage') {
               steps {
                    echo 'Step 2. Second time Hello'
                    echo 'Step 3. Third time Hello'
               }
          }
     }
}
