pipeline {
           agent any
           stages {
                stage("Checkout") {
                     steps {
                          scm
                     }
                }
		   stage("hello-world") { 
			   steps {
				   echo "Hello world!"
			   }
		   }
           }
      }
